[package]
name = "csvsplit"
version = "0.1.0"
authors = ["Mohamed Meftah <mohamed-ted@live.com>"]

[dependencies]
csv = "1"
num_cpus = "1.8.0"
threadpool = "1.7.1"
config = "0.9"
serde_derive = "^1.0.8"
serde = "^1.0.8"